### ISSUE TITLE
some letters used in Spanish are not in the resource pack (i use 1.1)

### ISSUE THREAD

**Issue by bendolo** [xlifi/MinecraftTen#5]
### Unicode font

- [X] I am sure that "Force Unicode Font" option is OFF

### Requested characters

á é í ó ú ñ ü ¡ ¿

### What resourcepack version do you use? You can find it in archive's name and in resourcepack's description in game.

1.0

### Where did you download the resourcepack?

https://modrinth.com/resourcepack/mc10

**Comment by hugoo-og** [comment]
Siempre nos ignoran 😭

**Comment by HF1NaCl** [comment]
¿De qué hablas? Podrías probar el fork que hice, para ver si está al español al 100%, porque con las pruebas que hice, ahora debe estar funcionando.
https://github.com/HF1NaCl/MinecraftTen

**Comment by bendolo** [comment]
gracias por el fork amigazo
