### ISSUE TITLE
[:abc:] 

### ISSUE THREAD

**Issue by hugoo-og** [xlifi/MinecraftTen#7]
### Unicode font

- [X] I am sure that "Force Unicode Font" option is OFF

### Requested characters

á é í ó ú ñ

### What resourcepack version do you use? You can find it in archive's name and in resourcepack's description in game.

1.0

### Where did you download the resourcepack?

https://modrinth.com/resourcepack/mc10

**Comment by HF1NaCl** [comment]
Take a look about the fork I made, It includes the requested characters.
https://github.com/HF1NaCl/MinecraftTen
